/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bridgelabz.indianstatecensusanalyser;

import org.junit.Test;

import com.bridgelabz.indianstatecensusanalyser.IndianStatesCensusCSV;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        IndianStatesCensusCSV classUnderTest = new IndianStatesCensusCSV();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
